package com.github.dhc.framework.hom.annotation;

import com.github.dhc.framework.hom.hbase.RowkeyProvider;
import com.google.common.collect.Sets;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.math.BigInteger;
import java.util.Set;

/**
 * Created by hcdeng on 17-8-25.
 * Desc: annotate the rowkey field of an htable
 * every po should have one and only one rowkey, or a RowKeyNotDefineException
 * will be thrown when loading HTableDefinition
 */
@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
public @interface RowKey {

    /**
     * for auto generation, rowkey must be one of the following types
     */
    Set<Class<?>> ALLOWED_ROWKEY_TYPES = Sets.newHashSet(int.class, Integer.class,
            long.class, Long.class,
            BigInteger.class, String.class
    );

    /**
     * when this value is true, the rowkey will be automatically generated if it's
     * not set with a not-null value
     * @return
     */
     boolean auto() default true;

    /**
     * When auto is true, rowkey will be be automatically generated by the rowkey provider
     * if set, or else just by system time. However, if the rowkey field is set by user
     * with a not-null value, then the auto and provider set here will be ignored.
     * @return
     */
     Class<? extends RowkeyProvider<?, ?>>[] provider() default {};
}
